### ISSUE TITLE
PING A,B: An unexpected deviation from the native call in argument parsing mode

### ISSUE THREAD

**Issue by yecril71pl** [mklement0/Native#10]
```powershell
PING A,B
IE PING A,B
```
> Ping request could not find host A,B.
> Ping request could not find host A.

**Comment by mklement0** [comment]
True, but that can't be helped, because by the time `ie` sees argument `A,B`, it sees an _array_, whose elements it then passes as individual arguments to the external executable.

That's a good illustration of why a  proper engine-level fix is the preferable solution.

The workaround is to use quoting:

```
ie ping 'a,b'
```

I'll add a note to the read-me.

**Comment by mklement0** [comment]
Thanks for the heads-up.

I've summarized the known limitations in https://github.com/mklement0/Native/blob/master/README.md#known-limitations, which is now a subsection of a new overview section that briefly introduces the commands and links to their detailed descriptions.
